name: ML Assignment CI

on:
  push:
    branches:
      - kernelridge

jobs:
  run-models:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Decision Tree training (train.py)
        run: |
          echo "Running train.py (DecisionTree)..."
          python train.py --n_runs 5 --test_size 0.2

      - name: Run Kernel Ridge training (train2.py)
        run: |
          echo "Running train2.py (KernelRidge)..."
          python train2.py --n_runs 5 --test_size 0.2
